#!/usr/bin/env python3
"""Discovery-only LP for a circuit-binomial certificate of Delta_b.

The target is shifted to positive edge-floor variables y_e=1+w_e.  We ask
whether it lies in the cone generated by nonnegative monomials and
y^alpha*(y^C-1) for the six cycles of the b-deleted four-route book.
SciPy is used only to discover a candidate; promoted evidence must replay an
exact integer/rational certificate using the standard library.
"""

from __future__ import annotations

from itertools import combinations, combinations_with_replacement, product
from pathlib import Path
import argparse
import sys

import numpy as np
from scipy.optimize import linprog
from scipy.sparse import coo_matrix


EVIDENCE = (
    Path(__file__).parents[1]
    / "campaigns"
    / "opg-1757-transverse-lift-round7"
    / "evidence"
)
sys.path.insert(0, str(EVIDENCE))

from verify_c_zero_fibre import (  # noqa: E402
    EDGES,
    add,
    derivative,
    multiply,
    reconstruct_original,
    restrict_original_zero,
)


B_EDGE = (0, 4)
ACTIVE_EDGES = tuple(edge for edge in EDGES if edge != B_EDGE)
ACTIVE_INDEX = {edge: index for index, edge in enumerate(ACTIVE_EDGES)}


def shifted_to_edge_floors(poly):
    """Substitute w_e=y_e-1 and drop the identically zero b coordinate."""
    shifted = {}
    b_index = EDGES.index(B_EDGE)
    for monomial, coefficient in poly.items():
        assert monomial[b_index] == 0
        terms = {(0,) * len(ACTIVE_EDGES): coefficient}
        for edge, old_index in zip(ACTIVE_EDGES, (i for i in range(8) if i != b_index)):
            for _ in range(monomial[old_index]):
                new_terms = {}
                slot = ACTIVE_INDEX[edge]
                for exponent, value in terms.items():
                    raised = list(exponent)
                    raised[slot] += 1
                    raised = tuple(raised)
                    new_terms[raised] = new_terms.get(raised, 0) + value
                    new_terms[exponent] = new_terms.get(exponent, 0) - value
                terms = {key: value for key, value in new_terms.items() if value}
        for exponent, value in terms.items():
            shifted[exponent] = shifted.get(exponent, 0) + value
    return {key: value for key, value in shifted.items() if value}


def book_cycles():
    cycles = []
    for size in range(3, len(ACTIVE_EDGES) + 1):
        for subset in combinations(ACTIVE_EDGES, size):
            degrees = {vertex: 0 for vertex in range(5)}
            for left, right in subset:
                degrees[left] += 1
                degrees[right] += 1
            if all(degree in (0, 2) for degree in degrees.values()) and sum(
                degree == 2 for degree in degrees.values()
            ) == size:
                cycles.append(tuple(ACTIVE_INDEX[edge] for edge in subset))
    assert len(cycles) == 6
    return cycles


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--order", type=int, choices=(1, 2, 3), default=1)
    parser.add_argument("--include-a", action="store_true")
    parser.add_argument("--include-route-derivatives", action="store_true")
    parser.add_argument("--laurent-shift", type=int, choices=(0, 1, 2), default=0)
    args = parser.parse_args()
    deletion, connectivity, _, _ = reconstruct_original()
    a_slope = derivative(deletion, (B_EDGE,))
    c_zero = restrict_original_zero(deletion, B_EDGE)
    d_slope = derivative(connectivity, (B_EDGE,))
    e_zero = restrict_original_zero(connectivity, B_EDGE)
    delta = add(multiply(a_slope, e_zero), multiply(d_slope, c_zero), -1)
    shifted = shifted_to_edge_floors(delta)

    maximum_grid_degree = 2 + args.laurent_shift
    target_shift = (args.laurent_shift,) * len(ACTIVE_EDGES)
    shifted_target = {
        tuple(degree + args.laurent_shift for degree in exponent): coefficient
        for exponent, coefficient in shifted.items()
    }
    nodes = tuple(product(range(maximum_grid_degree + 1), repeat=len(ACTIVE_EDGES)))
    node_index = {node: index for index, node in enumerate(nodes)}
    cycles = book_cycles()
    generators = []
    for order in range(1, args.order + 1):
        for cycle_indices in combinations_with_replacement(range(len(cycles)), order):
            multiplicities = tuple(
                sum(index in cycles[cycle_index] for cycle_index in cycle_indices)
                for index in range(len(ACTIVE_EDGES))
            )
            if any(value > maximum_grid_degree for value in multiplicities):
                continue
            base_ranges = tuple(
                range(maximum_grid_degree + 1 - value) for value in multiplicities
            )
            for base in product(*base_ranges):
                polynomial = {base: 1}
                for cycle_index in cycle_indices:
                    cycle_set = set(cycles[cycle_index])
                    next_polynomial = {}
                    for exponent, coefficient in polynomial.items():
                        raised = tuple(
                            degree + int(index in cycle_set)
                            for index, degree in enumerate(exponent)
                        )
                        next_polynomial[raised] = next_polynomial.get(raised, 0) + coefficient
                        next_polynomial[exponent] = next_polynomial.get(exponent, 0) - coefficient
                    polynomial = {
                        exponent: coefficient
                        for exponent, coefficient in next_polynomial.items()
                        if coefficient
                    }
                generators.append((cycle_indices, base, polynomial))

    if args.include_a or args.include_route_derivatives:
        shifted_a = shifted_to_edge_floors(a_slope)

        def multiply_active(left, right):
            result = {}
            for left_exponent, left_coefficient in left.items():
                for right_exponent, right_coefficient in right.items():
                    exponent = tuple(
                        left_degree + right_degree
                        for left_degree, right_degree in zip(left_exponent, right_exponent)
                    )
                    if any(degree > maximum_grid_degree for degree in exponent):
                        continue
                    result[exponent] = result.get(exponent, 0) + (
                        left_coefficient * right_coefficient
                    )
            return {key: value for key, value in result.items() if value}

        a_products = []
        if args.include_a:
            a_products.extend(
                [("A", shifted_a), ("A2", multiply_active(shifted_a, shifted_a))]
            )
            for cycle_index, cycle in enumerate(cycles):
                cycle_exponent = tuple(
                    int(index in cycle) for index in range(len(ACTIVE_EDGES))
                )
                cycle_polynomial = {
                    cycle_exponent: 1,
                    (0,) * len(ACTIVE_EDGES): -1,
                }
                a_products.append(
                    (f"A*C{cycle_index}", multiply_active(shifted_a, cycle_polynomial))
                )

        if args.include_route_derivatives:
            route_slots = (
                (ACTIVE_INDEX[(0, 1)], ACTIVE_INDEX[(0, 2)]),
                (ACTIVE_INDEX[(1, 3)], ACTIVE_INDEX[(2, 3)]),
                (ACTIVE_INDEX[(1, 4)], ACTIVE_INDEX[(2, 4)]),
                (ACTIVE_INDEX[(1, 2)],),
            )
            zero = (0,) * len(ACTIVE_EDGES)

            def route_monomial(route_indices):
                exponent = [0] * len(ACTIVE_EDGES)
                for route_index in route_indices:
                    for slot in route_slots[route_index]:
                        exponent[slot] = 1
                return tuple(exponent)

            for omitted in range(4):
                retained = tuple(index for index in range(4) if index != omitted)
                derivative_poly = {route_monomial(retained): 1, zero: 2}
                for route_index in retained:
                    exponent = route_monomial((route_index,))
                    derivative_poly[exponent] = derivative_poly.get(exponent, 0) - 1
                a_products.append((f"B{omitted}", derivative_poly))

        for name, factor_polynomial in a_products:
            if not factor_polynomial:
                continue
            maximum_degrees = tuple(
                max(exponent[index] for exponent in factor_polynomial)
                for index in range(len(ACTIVE_EDGES))
            )
            for base in product(
                *(range(maximum_grid_degree + 1 - degree) for degree in maximum_degrees)
            ):
                polynomial = {
                    tuple(left + right for left, right in zip(exponent, base)): coefficient
                    for exponent, coefficient in factor_polynomial.items()
                }
                generators.append(((name,), base, polynomial))

    # target = residual + inflow - outflow, residual>=0, so
    # inflow-outflow <= target at every monomial node.
    rows, columns, values = [], [], []
    for column, (_, _, polynomial) in enumerate(generators):
        for exponent, coefficient in polynomial.items():
            rows.append(node_index[exponent])
            columns.append(column)
            values.append(float(coefficient))
    matrix = coo_matrix(
        (values, (rows, columns)), shape=(len(nodes), len(generators))
    ).tocsr()
    target_vector = np.array([float(shifted_target.get(node, 0)) for node in nodes])
    result = linprog(
        np.zeros(len(generators)),
        A_ub=matrix,
        b_ub=target_vector,
        bounds=(0, None),
        method="highs",
    )
    print({
        "success": bool(result.success),
        "status": int(result.status),
        "message": result.message,
        "shifted_terms": len(shifted),
        "nodes": len(nodes),
        "generators": len(generators),
        "cycles": len(cycles),
        "order": args.order,
        "include_a": args.include_a,
        "include_route_derivatives": args.include_route_derivatives,
        "laurent_shift": args.laurent_shift,
    })
    if not result.success:
        return

    generator_values = [
        (generator, value)
        for generator, value in zip(generators, result.x)
        if value > 1e-8
    ]
    balance = matrix @ result.x
    residual = target_vector - balance
    print({
        "positive_generators": len(generator_values),
        "positive_residuals": int(np.count_nonzero(residual > 1e-8)),
        "minimum_residual": float(residual.min()),
        "maximum_flow": float(result.x.max(initial=0)),
    })
    for (cycle_indices, base, _), value in sorted(
        generator_values, key=lambda item: -item[1]
    )[:40]:
        print("generator", cycle_indices, base, value)


if __name__ == "__main__":
    main()
