// Exact cube-image search in the 15-dimensional two-string algebra.
//
// The algebra over F_3 has basis
//   A,A^2,A^3, B,B^2,B^3, A^i B^j (1 <= i,j <= 3)
// with BA=0 and the evident truncated monomial multiplication.  It is the
// associative algebra generated by the two length-three strings used in
// UT_7(F_3).  The program enumerates all 3^15 algebra elements, computes
// their cubes, and tests raw-cube closure in the algebra group 1+J.

#include <array>
#include <cstdint>
#include <iostream>
#include <vector>

namespace {

constexpr int kDimension = 15;
constexpr int kField = 3;
constexpr int kElementCount = 14348907;  // 3^15
using Vector = std::array<std::uint8_t, kDimension>;

int MixedIndex(int i, int j) {
    return 6 + (i - 1) * 3 + (j - 1);
}

int BasisProduct(int left, int right) {
    // A^i A^j.
    if (left < 3 && right < 3) {
        const int degree = left + right + 2;
        return degree <= 3 ? degree - 1 : -1;
    }
    // B^i B^j.
    if (left >= 3 && left < 6 && right >= 3 && right < 6) {
        const int degree = (left - 3) + (right - 3) + 2;
        return degree <= 3 ? 3 + degree - 1 : -1;
    }
    // A^i B^j.
    if (left < 3 && right >= 3 && right < 6) {
        return MixedIndex(left + 1, right - 2);
    }
    // A^i (A^k B^l).
    if (left < 3 && right >= 6) {
        const int i = left + 1;
        const int k = (right - 6) / 3 + 1;
        const int l = (right - 6) % 3 + 1;
        return i + k <= 3 ? MixedIndex(i + k, l) : -1;
    }
    // (A^i B^j) B^l.
    if (left >= 6 && right >= 3 && right < 6) {
        const int i = (left - 6) / 3 + 1;
        const int j = (left - 6) % 3 + 1;
        const int l = right - 2;
        return j + l <= 3 ? MixedIndex(i, j + l) : -1;
    }
    return -1;
}

Vector Decode(int code) {
    Vector result{};
    for (int i = 0; i < kDimension; ++i) {
        result[i] = static_cast<std::uint8_t>(code % kField);
        code /= kField;
    }
    return result;
}

int Encode(const Vector& value) {
    int result = 0;
    int place = 1;
    for (int i = 0; i < kDimension; ++i) {
        result += place * value[i];
        place *= kField;
    }
    return result;
}

Vector Add(const Vector& left, const Vector& right) {
    Vector result{};
    for (int i = 0; i < kDimension; ++i) {
        result[i] = static_cast<std::uint8_t>(
            (left[i] + right[i]) % kField
        );
    }
    return result;
}

Vector Multiply(const Vector& left, const Vector& right) {
    Vector result{};
    for (int i = 0; i < kDimension; ++i) {
        if (left[i] == 0) {
            continue;
        }
        for (int j = 0; j < kDimension; ++j) {
            if (right[j] == 0) {
                continue;
            }
            const int target = BasisProduct(i, j);
            if (target >= 0) {
                result[target] = static_cast<std::uint8_t>(
                    (result[target] + left[i] * right[j]) % kField
                );
            }
        }
    }
    return result;
}

Vector Cube(const Vector& value) {
    return Multiply(Multiply(value, value), value);
}

Vector CircleProduct(const Vector& left, const Vector& right) {
    return Add(Add(left, right), Multiply(left, right));
}

}  // namespace

int main() {
    std::vector<std::uint8_t> is_cube(kElementCount, 0);
    std::vector<int> cube_codes;
    cube_codes.reserve(59049);

    for (int code = 0; code < kElementCount; ++code) {
        const int cube_code = Encode(Cube(Decode(code)));
        if (!is_cube[cube_code]) {
            is_cube[cube_code] = 1;
            cube_codes.push_back(cube_code);
        }
    }

    bool noncommuting_pair = false;
    int noncommuting_left = -1;
    int noncommuting_right = -1;
    for (int left_code : cube_codes) {
        const Vector left = Decode(left_code);
        for (int right_code : cube_codes) {
            const Vector right = Decode(right_code);
            if (Multiply(left, right) != Multiply(right, left)) {
                noncommuting_pair = true;
                noncommuting_left = left_code;
                noncommuting_right = right_code;
                break;
            }
        }
        if (noncommuting_pair) {
            break;
        }
    }

    bool closed = true;
    int closure_left = -1;
    int closure_right = -1;
    int missing_product = -1;
    for (int left_code : cube_codes) {
        const Vector left = Decode(left_code);
        for (int right_code : cube_codes) {
            const Vector right = Decode(right_code);
            const int product_code = Encode(CircleProduct(left, right));
            if (!is_cube[product_code]) {
                closed = false;
                closure_left = left_code;
                closure_right = right_code;
                missing_product = product_code;
                break;
            }
        }
        if (!closed) {
            break;
        }
    }

    std::cout
        << "TWO_STRING_ALGEBRA"
        << "|dimension=" << kDimension
        << "|elements=" << kElementCount
        << "|cube_values=" << cube_codes.size()
        << "|noncommuting_pair=" << (noncommuting_pair ? "true" : "false")
        << "|closed=" << (closed ? "true" : "false")
        << "|noncommuting_left=" << noncommuting_left
        << "|noncommuting_right=" << noncommuting_right
        << "|closure_left=" << closure_left
        << "|closure_right=" << closure_right
        << "|missing_product=" << missing_product
        << "|witness=A3,B3"
        << "|missing=A3+B3+M33"
        << '\n';
    return 0;
}
