# Optional full-library audit at order 3^7 = 2187.
#
# This script requires the complete GAP Small Groups Library data for order
# 2187 (9,310 groups).  It is intentionally separate from the default test
# suite because compact GAP installations often omit the p^7 data files.

SizeScreen([100000, 100000]);;

AssertOrFail := function(condition, message)
    if not condition then
        Error(message);
    fi;
end;;

order := 2187;;
AssertOrFail(
    NumberSmallGroups(order) = 9310,
    "complete SmallGrp data for order 2187 is unavailable"
);

exp_nine := 0;;
class_counts := rec(c4 := 0, c5 := 0, c6 := 0);;
nonabelian_power_group := 0;;
class_five_ids := [];;
class_five_bad_z3 := [];;

for identifier in [1 .. NumberSmallGroups(order)] do
    group := SmallGroup(order, identifier);
    if Exponent(group) = 9 then
        exp_nine := exp_nine + 1;
        class := NilpotencyClassOfGroup(group);
        if class = 4 then
            class_counts.c4 := class_counts.c4 + 1;
        elif class = 5 then
            class_counts.c5 := class_counts.c5 + 1;
            Add(class_five_ids, identifier);
        elif class = 6 then
            class_counts.c6 := class_counts.c6 + 1;
        fi;

        if class >= 4 then
            # GAP's Agemo(group, 3) is the verbal subgroup generated by
            # all cubes, not merely by cubes of the chosen generators.
            power_group := Agemo(group, 3);
            if not IsAbelian(power_group) then
                nonabelian_power_group := nonabelian_power_group + 1;
            fi;
        fi;

        if class = 5 then
            upper := UpperCentralSeries(group);
            # UpperCentralSeries is returned in descending order
            # [G,Z_4,Z_3,Z_2,Z_1,1] for a class-five group.
            z3 := upper[3];
            if ForAny(
                GeneratorsOfGroup(Agemo(group, 3)),
                element -> not element in z3
            ) then
                Add(class_five_bad_z3, identifier);
            fi;
        fi;
    fi;
od;

AssertOrFail(class_counts.c4 = 1181, "unexpected class-4 count");
AssertOrFail(class_counts.c5 = 26, "unexpected class-5 count");
AssertOrFail(class_counts.c6 = 0, "unexpected class-6 count");
AssertOrFail(exp_nine = 8302, "unexpected exponent-nine count");
AssertOrFail(
    nonabelian_power_group = 0,
    "an order-2187 exponent-nine group has nonabelian cube subgroup"
);
AssertOrFail(
    Length(class_five_bad_z3) = 0,
    "a class-five candidate has cubes outside Z_3"
);

Print(
    "ORDER2187|groups=9310|exp9=", exp_nine,
    "|class4=", class_counts.c4,
    "|class5=", class_counts.c5,
    "|class6=", class_counts.c6,
    "|nonabelian_cube_subgroups=", nonabelian_power_group,
    "|class5_cubes_outside_Z3=", Length(class_five_bad_z3),
    "\n"
);
Print("CLASS5_IDS|", class_five_ids, "\n");
Print("DONE\n");
QUIT;
