# Exhaustive p=3 regression for the all-quotients no-go theorem.
#
# Seed A = UT_3(F_3), W = A wr C_3.  For every normal subgroup N of W,
# the image of the raw cube set is tested for closure by comparing its
# cardinality with the image of the subgroup generated by all cubes.

SizeScreen([100000, 100000]);;

AssertOrFail := function(condition, message)
    if not condition then
        Error(message);
    fi;
end;;

field := GF(3);;
matrix := IdentityMat(3, field);;
matrix[1][2] := One(field);;
x := matrix;;
matrix := IdentityMat(3, field);;
matrix[2][3] := One(field);;
y := matrix;;
matrix_seed := Group(x, y);;
seed := Image(IsomorphismPermGroup(matrix_seed));;
permutation_wreath := WreathProduct(seed, Group((1, 2, 3)));;
wreath := Image(IsomorphismPcGroup(permutation_wreath));;

elements := Elements(wreath);;
cube_values := Set(elements, element -> element^3);;
cube_group := Group(cube_values);;
central_base := Centre(cube_group);;
diagonal_centre := DerivedSubgroup(cube_group);;

AssertOrFail(Size(seed) = 27, "wrong seed order");
AssertOrFail(Exponent(seed) = 3, "wrong seed exponent");
AssertOrFail(Size(wreath) = 59049, "wrong wreath order");
AssertOrFail(Length(cube_values) = 219, "wrong cube-value count");
AssertOrFail(Size(cube_group) = 243, "wrong generated cube-group order");
AssertOrFail(Size(central_base) = 27, "wrong K order");
AssertOrFail(Size(diagonal_centre) = 3, "wrong diagonal-centre order");
AssertOrFail(
    Set(
        Concatenation(
            Difference(Elements(cube_group), Elements(central_base)),
            Elements(diagonal_centre)
        )
    ) = cube_values,
    "raw cube set is not (H minus K) union Delta(U)"
);

normal_subgroups := NormalSubgroups(wreath);;
quotient_map := fail;;
closed_count := 0;;
closed_nonabelian_count := 0;;
closed_k_branch_count := 0;;
closed_outside_k_branch_count := 0;;
delta_killed_count := 0;;

for normal in normal_subgroups do
    intersection := Intersection(normal, cube_group);;
    quotient_map := NaturalHomomorphismByNormalSubgroup(wreath, normal);;
    image_values := Set(
        cube_values,
        value -> Image(quotient_map, value)
    );;
    image_generated_order := Size(cube_group) / Size(intersection);;
    is_closed := Length(image_values) = image_generated_order;;
    kills_diagonal := IsSubgroup(normal, diagonal_centre);;

    if is_closed and not kills_diagonal then
        closed_nonabelian_count := closed_nonabelian_count + 1;;
    fi;
    if kills_diagonal then
        delta_killed_count := delta_killed_count + 1;;
    fi;

    if is_closed then
        closed_count := closed_count + 1;;
        AssertOrFail(
            kills_diagonal,
            "closed cube image does not kill Delta(U)"
        );
        if IsSubgroup(central_base, intersection) then
            AssertOrFail(
                intersection = central_base,
                "closed L <= K branch does not force L = K"
            );
            closed_k_branch_count := closed_k_branch_count + 1;;
        else
            closed_outside_k_branch_count :=
                closed_outside_k_branch_count + 1;;
        fi;
    fi;
od;

AssertOrFail(
    closed_nonabelian_count = 0,
    "a normal quotient has a closed nonabelian cube subgroup"
);
AssertOrFail(
    closed_count =
        closed_k_branch_count + closed_outside_k_branch_count,
    "closed-quotient branch counts do not add up"
);

Print(
    "EXP_P_ALL_QUOTIENTS_P3",
    "|wreath_order=", Size(wreath),
    "|normal_subgroups=", Length(normal_subgroups),
    "|cube_values=", Length(cube_values),
    "|cube_group_order=", Size(cube_group),
    "|K_order=", Size(central_base),
    "|DeltaU_order=", Size(diagonal_centre),
    "|delta_killed=", delta_killed_count,
    "|closed=", closed_count,
    "|closed_L_le_K=", closed_k_branch_count,
    "|closed_L_outside_K=", closed_outside_k_branch_count,
    "|closed_nonabelian=", closed_nonabelian_count,
    "\n"
);
Print("DONE\n");
QUIT;
